version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: >
      bash -c "sh start_django.sh"
    volumes:
      - .:/code
      - ~/.ssh:/root/.ssh:ro
      - /private/tmp:/private/tmp/
    ports:
      - "8000:8000"
    depends_on:
      - db
  gui:
    build: .
    command: >
        bash -c "sh start_electron.sh"
    environment:
      - DISPLAY:$DISPLAY
    volumes:
      - .:/code
      - ~/.Xauthority:/root/.Xauthority:rw
    depends_on:
      - web

